# 公有库地址
source 'https://github.com/CocoaPods/Specs.git'

install!'cocoapods',:deterministic_uuids=>false
platform :ios, '10.0'
#use_frameworks!
use_modular_headers!
inhibit_all_warnings! # 忽略所有依赖库的警告

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 10.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end
    end
  end
end

target 'MVVMBaseSwift_Example' do
  pod 'MVVMBaseSwift', :path => '../'

end
